[package]
name = "jackup"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
log = "0.4.27"
anyhow = "1.0.99"
time = "0.3.43"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
uuid = "1.18.1"
hostname = "0.4.1"
