[package]
name = "jackup"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
log = "0.4.27"
anyhow = "1.0.99"
time = { version = "0.3.43", features = ["formatting", "parsing"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
uuid = { version = "1.18.1", features = ["v4"]}
hostname = "0.4.1"
home = "0.5.11"
rustyline = "17.0.2"
env_logger = "0.11"
walkdir = "2.5.0"
tar = "0.4.44"
zstd = "0.13.3"
globset = "0.4.18"
